name: Report a Script Issue
description: Use this form to report issues related to scripts. For other types of inquiries, please utilize the Discussions section.
body:
  - type: markdown
    attributes:
      value: |
        **Please Note:** We value your contribution and want to address your concerns efficiently. To help us do that, please consider the following:
        - Check the closed issues before submitting a new one. If your issue has been addressed in a closed issue, kindly add a comment there instead of opening a new issue.
        - Note that we only provide support for the default Linux distribution intended to be used with the app in question.
        - If you encounter the error message `[ERROR] in line 23: exit code *: while executing command "$@" > /dev/null 2>&1`, try running the script in verbose mode to better identify the issue.
        - For suggestions, questions, or to request new features or scripts, please use our [Discussions section.](https://github.com/tnware/Proxmox/discussions)
  - type: input
    id: guidelines
    attributes:
      label: Have you reviewed the guidelines above? Please type 'yes' to confirm.
      placeholder: 'yes'
    validations:
      required: true
  - type: textarea
    id: bug
    attributes:
      label: Describe the issue in a clear and concise manner.
    validations:
      required: true
  - type: dropdown
    id: settings
    validations:
      required: true
    attributes:
      label: Which settings are you using?
      options:
        - Default Settings
        - Advanced Settings
  - type: markdown
    attributes:
      value: (If using Advanced Settings, please try with Default Settings to see if the issue persists before submitting)
  - type: dropdown
    id: distribution
    validations:
      required: true
    attributes:
      label: What Linux distribution are you using?
      options:
        - Debian 11
        - Debian 12
        - Ubuntu 20.04
        - Ubuntu 22.04
        - Ubuntu 23.10
  - type: textarea
    id: screenshot
    attributes:
      label: If applicable, please provide screenshots or a code snippet to illustrate the issue. Wrap code snippets with three backticks for clarity.
      placeholder: Code blocks begin and end with three backticks above and below the code.
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: Please outline the steps to reproduce the issue.
      placeholder: First, do this... Then, do that...
    validations:
      required: false
